/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistem.cafe;

import Koneksi.Db_Koneksi;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Risqi Bagus Palevi
 */
public class Inventory extends javax.swing.JFrame {
    
    private DefaultTableModel model;
    String menu;
    int harga_menu, harga_pokok;

    /**
     * Creates new form Inventory
     */
    public Inventory() {
        initComponents();
        model = new DefaultTableModel();
        tbl_makanan.setModel(model);
        model.addColumn("menu");
        model.addColumn("harga_menu");
        model.addColumn("harga_pokok");
        getData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMenu = new javax.swing.JTextField();
        txtHargaJual = new javax.swing.JTextField();
        txtHargaPokok = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_makanan = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(250, 100));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(960, 580));
        jPanel1.setLayout(null);

        logo.setFont(new java.awt.Font("Nunito Sans Black", 2, 48)); // NOI18N
        logo.setForeground(new java.awt.Color(0, 204, 204));
        logo.setText("SiPOZKu");
        jPanel1.add(logo);
        logo.setBounds(20, 410, 240, 90);

        jLabel1.setBackground(new java.awt.Color(0, 51, 255));
        jLabel1.setFont(new java.awt.Font("Work Sans", 1, 36)); // NOI18N
        jLabel1.setText("INPUT DATA MENU ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(31, 36, 360, 43);

        jLabel7.setText("Nama Menu");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(31, 104, 77, 14);
        jPanel1.add(txtMenu);
        txtMenu.setBounds(112, 101, 210, 20);
        jPanel1.add(txtHargaJual);
        txtHargaJual.setBounds(112, 140, 210, 20);
        jPanel1.add(txtHargaPokok);
        txtHargaPokok.setBounds(112, 178, 210, 20);

        jLabel3.setText("Harga Pokok");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(31, 181, 60, 14);

        jLabel2.setText("Harga Jual");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(31, 143, 77, 14);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setText("INPUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 240, 90, 30);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(230, 240, 90, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Klik Pada Record untuk mengedit, mengupdate, dan menghapus data.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(370, 100, 490, 15);

        tbl_makanan.setFont(new java.awt.Font("Work Sans", 0, 12)); // NOI18N
        tbl_makanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "menu", "harga_menu", "harga_pokok"
            }
        ));
        tbl_makanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_makananMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl_makananMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_makanan);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(370, 140, 540, 340);

        jButton4.setText("Dashboard");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(780, 40, 130, 30);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(130, 240, 90, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\Kuliah\\Aset Gambar Projek AKhir Pmvs\\bg new.png")); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 950, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       updateData();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        GoToDashboard();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        saveData();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        deleteData();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tbl_makananMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_makananMouseEntered
        
    }//GEN-LAST:event_tbl_makananMouseEntered

    private void tbl_makananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_makananMouseClicked
        dataSelect();
    }//GEN-LAST:event_tbl_makananMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory().setVisible(true);
            }
        });
    }
    
    private void GoToDashboard(){
        this.setVisible(false);
        new Dashboard().setVisible(true);
    }
    
    public void Reset(){
        menu = "";
        harga_menu = 0;
        harga_pokok = 0;
        
        txtMenu.setText("");
        txtHargaJual.setText("");
        txtHargaPokok.setText("");
    }
    
    public void loadData(){
        
        menu = txtMenu.getText();
        harga_menu = Integer.parseInt(txtHargaJual.getText());
        harga_pokok = Integer.parseInt(txtHargaPokok.getText());
    }
    
    
    public void getData(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        try{
            Statement stat = (Statement) Db_Koneksi.getKoneksi().createStatement();
            String sql = "Select * from tbl_makanan";
            ResultSet res = stat.executeQuery(sql);
            
            while(res.next()){
                Object[] obj = new Object[3];
                obj[0] = res.getString("menu");
                obj[1] = res.getString("harga_menu");
                obj[2] = res.getString("harga_pokok");
                
                model.addRow(obj);
            }
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }
    
     public void saveData(){
         
         loadData();
        
        try{
            Statement stat = (Statement) Db_Koneksi.getKoneksi().createStatement();
            String sql = "insert into tbl_makanan values ('"+menu+"', '"+harga_menu+"', '"+harga_pokok+"')";
            PreparedStatement p = (PreparedStatement) Db_Koneksi.getKoneksi().prepareStatement(sql);
            p.executeUpdate();
            getData();
            
            Reset();
            JOptionPane.showMessageDialog(null, "Menu berhasil disimpan!");
            
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage());
        }              
    }
     
    public void dataSelect(){
        int i = tbl_makanan.getSelectedRow();
        if (i == -1){
            return;
        }
        txtMenu.setText(""+model.getValueAt(i, 0));
        txtHargaJual.setText(""+model.getValueAt(i, 1));
        txtHargaPokok.setText(""+model.getValueAt(i, 2));   
    }
    
    public void updateData(){
       loadData();
        
        try {
            Statement stat = (Statement) Db_Koneksi.getKoneksi().createStatement();
            String sql = "update tbl_makanan set menu = '"+menu+"',harga_menu = '"+harga_menu+"',harga_pokok = '"+harga_pokok+"' where menu = '"+menu+"'";
            
            PreparedStatement p = (PreparedStatement) Db_Koneksi.getKoneksi().prepareStatement(sql);
            p.executeUpdate();
            getData();
            
            Reset();
            JOptionPane.showMessageDialog(null, "Menu berhasil diupdate!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public void deleteData(){
        loadData();
        
        int pesan = JOptionPane.showConfirmDialog(null, "Anda yakin menghapus menu " +menu+"?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION);
        if(pesan == JOptionPane.OK_OPTION){
            
            try {
                Statement stat = (Statement) Db_Koneksi.getKoneksi().createStatement();
                String sql = "delete from tbl_makanan where menu = '"+menu+"'";

                PreparedStatement p = (PreparedStatement) Db_Koneksi.getKoneksi().prepareStatement(sql);
                p.executeUpdate();
                getData();

                Reset();
                JOptionPane.showMessageDialog(null, "Menu berhasil dihapus!");
            } catch (SQLException e) {
              JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }
     
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JTable tbl_makanan;
    private javax.swing.JTextField txtHargaJual;
    private javax.swing.JTextField txtHargaPokok;
    private javax.swing.JTextField txtMenu;
    // End of variables declaration//GEN-END:variables

}