/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistem.cafe;

import javax.swing.table.DefaultTableModel;
import Koneksi.Db_Koneksi;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement; 
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.sql.Timestamp;

/**
 *
 * @author Risqi Bagus Palevi
 */
public class Order extends javax.swing.JFrame {

    /**
     * Creates new form Order
     */
    
    Date date= new Date();
    long time = date.getTime();
    Timestamp ts = new Timestamp(time);
    private DefaultTableModel model,model2;
    String fhasil, menu, cust, keterangan, finalhrgtotal, kode_transaksi,fkembalian, fkodetransaksi;
    int hasil, jumlah, jumlah2, harga_menu, harga_total=jumlah*harga_menu, bayar, kembalian;
    
    public Order() {
        
        initComponents();
        
        JOptionPane.showMessageDialog(null, "Petunjuk Menu ORDER : Input Kode Transaksi dan Nama Customer Terlebih Dahulu "
                        + "sebelum input Order!");
        
        model = new DefaultTableModel();
        temporder.setModel(model);
        model.addColumn("cust");
        model.addColumn("menu");
        model.addColumn("jumlah");
        model.addColumn("keterangan");
        model.addColumn("harga_menu");
        model.addColumn("harga_total");
        
        model2 = new DefaultTableModel();
        tbl_makanan.setModel(model2);
        model2.addColumn("menu");
        model2.addColumn("harga_menu");
        
        getDataMenu();
        getData();
        lastKTr();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCust = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtJml = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtKet = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_makanan = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        temporder = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtLabelHarga = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtBayar = new javax.swing.JTextField();
        txtKembalian = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtKTransaksiTerakhir = new javax.swing.JTextField();
        logo = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtHargaMenu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtHargaTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMenu = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtKodeTransaksi = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 100));
        setResizable(false);
        setSize(new java.awt.Dimension(950, 540));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Work Sans", 1, 36)); // NOI18N
        jLabel3.setText("ORDER PAGE ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 250, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Nama Customer");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 20));
        jPanel1.add(txtCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 110, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Jumlah");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        txtJml.setEditable(false);
        txtJml.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                txtJmlComponentAdded(evt);
            }
        });
        txtJml.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtJmlInputMethodTextChanged(evt);
            }
        });
        txtJml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJmlActionPerformed(evt);
            }
        });
        txtJml.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtJmlPropertyChange(evt);
            }
        });
        txtJml.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJmlKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJmlKeyTyped(evt);
            }
        });
        jPanel1.add(txtJml, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 110, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Keterangan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        txtKet.setEditable(false);
        jPanel1.add(txtKet, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 110, 50));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jButton4.setText("UPDATE PESANAN");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 110, 30));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton5.setText("INPUT PESANAN");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 110, 30));

        jPanel3.setBackground(new java.awt.Color(204, 229, 182));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_makanan.setFont(new java.awt.Font("Work Sans", 0, 12)); // NOI18N
        tbl_makanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "menu", "harga_menu"
            }
        ));
        tbl_makanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_makananMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_makanan);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 200, 430));

        temporder.setFont(new java.awt.Font("Work Sans", 0, 12)); // NOI18N
        temporder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "cust", "menu", "jumlah", "keterangan", "harga_menu", "harga_total"
            }
        ));
        temporder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                temporderMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(temporder);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 400, 220));

        jButton6.setText("Dashboard");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 130, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("DAFTAR MENU");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("DAFTAR PESANAN");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtLabelHarga.setBackground(new java.awt.Color(102, 102, 102));
        txtLabelHarga.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtLabelHarga.setForeground(new java.awt.Color(255, 255, 51));
        txtLabelHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLabelHargaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtLabelHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtLabelHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 200, 70));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setText("ORDER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 200, 70));

        txtBayar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel3.add(txtBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 190, 70));

        txtKembalian.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txtKembalian.setForeground(new java.awt.Color(0, 153, 0));
        jPanel3.add(txtKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 190, 70));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Total Transaksi Anda");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Uang Anda");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        jLabel1.setText("Kode Transaksi Terakhir : ");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtKTransaksiTerakhir.setEditable(false);
        jPanel3.add(txtKTransaksiTerakhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 70, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 680, 540));

        logo.setFont(new java.awt.Font("Nunito Sans Black", 2, 48)); // NOI18N
        logo.setForeground(new java.awt.Color(0, 204, 204));
        logo.setText("SiPOZKu");
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton7.setText("BATALKAN PESANAN");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 110, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Harga Menu");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        txtHargaMenu.setEditable(false);
        txtHargaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaMenuActionPerformed(evt);
            }
        });
        jPanel1.add(txtHargaMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 110, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Harga Total");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        txtHargaTotal.setEditable(false);
        txtHargaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaTotalActionPerformed(evt);
            }
        });
        txtHargaTotal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtHargaTotalPropertyChange(evt);
            }
        });
        jPanel1.add(txtHargaTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 110, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Menu");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        txtMenu.setEditable(false);
        txtMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMenuActionPerformed(evt);
            }
        });
        jPanel1.add(txtMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 110, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Kode Transaksi");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));
        jPanel1.add(txtKodeTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 110, 30));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton2.setText("DELETE MENU DARI PESANAN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 110, 30));

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setText("INPUT KODE TRANSAKSI DAN CUST.");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 230, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJmlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJmlActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        GoToDashboard();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtHargaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaMenuActionPerformed

    private void txtHargaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaTotalActionPerformed

    private void txtMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMenuActionPerformed
        JOptionPane.showMessageDialog(null, "Klik pada tabel Daftar Menu untuk input Menu!");
    }//GEN-LAST:event_txtMenuActionPerformed

    private void tbl_makananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_makananMouseClicked
        dataSelect();
    }//GEN-LAST:event_tbl_makananMouseClicked

    private void txtJmlPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtJmlPropertyChange
        
    }//GEN-LAST:event_txtJmlPropertyChange

    private void txtHargaTotalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtHargaTotalPropertyChange
        
    }//GEN-LAST:event_txtHargaTotalPropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if (txtBayar.getText().isEmpty() == true){
            JOptionPane.showMessageDialog(null, "Selesaikan Input atau Masukan Nominal Bayar!","Warning",JOptionPane.WARNING_MESSAGE);
        } else {
        saveDataToDetailTransaksi();
        Kembalian();
        truncateTable();
        txtCust.setText("");
        txtKodeTransaksi.setText("");
        jButton3.setEnabled(true);
        txtKodeTransaksi.setEditable(true);
        txtCust.setEditable(true);
        txtJml.setEditable(false);
        txtKet.setEditable(false);
        lastKTr();
        jButton7.setEnabled(false);
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtJmlComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_txtJmlComponentAdded
        //hitungHargaTotal();
    }//GEN-LAST:event_txtJmlComponentAdded

    private void txtJmlInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtJmlInputMethodTextChanged
        //hitungHargaTotal();
    }//GEN-LAST:event_txtJmlInputMethodTextChanged

    private void txtJmlKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJmlKeyTyped
      //hitungHargaTotal();
    }//GEN-LAST:event_txtJmlKeyTyped

    private void txtJmlKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJmlKeyPressed
        //hitungHargaTotal();
    }//GEN-LAST:event_txtJmlKeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
        hitungHargaTotal();
        saveData();
        countPriceDisplay();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        deleteData();
        countPriceDisplay();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void temporderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_temporderMouseClicked
        dataSelectOrder();
    }//GEN-LAST:event_temporderMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        updateData();
        countPriceDisplay();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        inputKode();
        lastKTr();
//        jButton3.setEnabled(false);
//        txtKodeTransaksi.setEditable(false);
//        txtCust.setEditable(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtLabelHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLabelHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLabelHargaActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //if (txtKodeTransaksi.getText().isEmpty() == true || txtLabelHarga.getText().isEmpty() == true)
        cancelMenu();
//        JOptionPane.showMessageDialog(null, "Pesanan dibatalkan");
//        txtCust.setText("");
//        txtKodeTransaksi.setText("");
//        jButton3.setEnabled(true);
//        txtKodeTransaksi.setEditable(true);
//        txtCust.setEditable(true);
//        txtJml.setEditable(false);
//        txtKet.setEditable(false);
//        lastKTr();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 
                new Order().setVisible(true);
                
                
            }
        });
    }
    
    public void inputKode(){
       kode_transaksi = txtKodeTransaksi.getText();
       cust = txtCust.getText();
       
        try{
            if (txtKodeTransaksi.getText().trim().isEmpty() == true || txtCust.getText().trim().isEmpty() == true) {
                JOptionPane.showMessageDialog(null, "Kode Transaksi atau Nama Cust Tidak Boleh Kosong", "Warning",JOptionPane.WARNING_MESSAGE);
            } else {
            Statement stat = (Statement) Db_Koneksi.getKoneksi().createStatement();
            String sql = "insert into transaksi values ('"+kode_transaksi+"', '"+ts+"', '"+cust+"' )";
            PreparedStatement p = (PreparedStatement) Db_Koneksi.getKoneksi().prepareStatement(sql);
            p.executeUpdate();
            getData();
             
            //Reset();
            JOptionPane.showMessageDialog(null, "Kode Transaksi dan Nama Customer berhasil disimpan!");
            jButton3.setEnabled(false);
            txtKodeTransaksi.setEditable(false);
            txtCust.setEditable(false);
            txtJml.setEditable(true);
            txtKet.setEditable(true);
            }

        }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage());
        } 
    }
    
    private void GoToDashboard(){
        this.setVisible(false);
        new Dashboard().setVisible(true);
    }
    
    public void getDataMenu(){
        model2.getDataVector().removeAllElements();
        model2.fireTableDataChanged();
        
        try{
            Statement stat = (Statement) Db_Koneksi.getKoneksi().createStatement();
            String sql = "Select * from tbl_makanan";
            ResultSet res = stat.executeQuery(sql);
            
            while(res.next()){
                Object[] obj = new Object[2];
                obj[0] = res.getString("menu");
                obj[1] = res.getString("harga_menu");
             
                model2.addRow(obj);
            }
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }
    
     public void getData(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        try{
            Statement stat = (Statement) Db_Koneksi.getKoneksi().createStatement();
            String sql = "Select * from temporder";
            ResultSet res = stat.executeQuery(sql);
            
            while(res.next()){
                Object[] obj = new Object[6];
                obj[0] = res.getString("cust");
                obj[1] = res.getString("menu");
                obj[2] = res.getString("jumlah");
                obj[3] = res.getString("keterangan");
                obj[4] = res.getString("harga_menu");
                obj[5] = res.getString("harga_total");

                model.addRow(obj);
            }
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }
     
     public void Reset(){
          
        menu = "";
        jumlah = 0;
        keterangan = "";
        harga_menu = 0;
        harga_total = 0;
            
        txtJml.setText("");
        txtKet.setText("");
        txtHargaMenu.setText("");
        txtHargaTotal.setText("");
        txtMenu.setText(" ");
    }
     
     
      public void loadData(){
        
        hitungHargaTotal();
        cust = txtCust.getText();
        menu = txtMenu.getText();
        keterangan = txtKet.getText();
        jumlah = Integer.parseInt(txtJml.getText());
        harga_menu = Integer.parseInt(txtHargaMenu.getText());
        harga_total = Integer.parseInt(txtHargaTotal.getText());
        kode_transaksi = txtKodeTransaksi.getText();
        
    }
      
      
      public void truncateTable(){
          try{
            Statement stat = (Statement) Db_Koneksi.getKoneksi().createStatement();
            String sql = "truncate table temporder";
            PreparedStatement p = (PreparedStatement) Db_Koneksi.getKoneksi().prepareStatement(sql);
            p.executeUpdate();
            getData();
            
            Reset();
            //JOptionPane.showMessageDialog(null, "Pesanan Terkonfirmasi");
            txtBayar.setText("");
            txtKembalian.setText("");
            
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage());
        }              
      }
      
      public void cancelMenu(){
          
          int pesan = JOptionPane.showConfirmDialog(null, "Anda Ingin Batalkan Pesanan?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION);
          if(pesan == JOptionPane.OK_OPTION){
            try{
              Statement stat = (Statement) Db_Koneksi.getKoneksi().createStatement();
              String sql = "truncate table temporder";
              PreparedStatement p = (PreparedStatement) Db_Koneksi.getKoneksi().prepareStatement(sql);
              p.executeUpdate();
              getData();

              Reset();
              //JOptionPane.showMessageDialog(null, "Pesanan Terkonfirmasi");

          }catch(SQLException err){
              JOptionPane.showMessageDialog(null, err.getMessage());
          }  

            try{
              Statement stat = (Statement) Db_Koneksi.getKoneksi().createStatement();
              String sql = "delete from transaksi order by kode_transaksi desc limit 1";
              PreparedStatement p = (PreparedStatement) Db_Koneksi.getKoneksi().prepareStatement(sql);
              p.executeUpdate();
              getData();

              Reset();
              //JOptionPane.showMessageDialog(null, "Pesanan Terkonfirmasi");
              txtBayar.setText("");
              txtKembalian.setText("");
              txtLabelHarga.setText("");

          }catch(SQLException err){
              JOptionPane.showMessageDialog(null, err.getMessage());
          } 
            
        JOptionPane.showMessageDialog(null, "Pesanan dibatalkan");
        txtCust.setText("");
        txtKodeTransaksi.setText("");
        jButton3.setEnabled(true);
        txtKodeTransaksi.setEditable(true);
        txtCust.setEditable(true);
        txtJml.setEditable(false);
        txtKet.setEditable(false);
        lastKTr();
        }
      }
      
      public void lastKTr(){
          try{
            Statement stat = (Statement) Db_Koneksi.getKoneksi().createStatement();
            String sql = "select kode_transaksi from transaksi order by kode_transaksi desc limit 1";
            PreparedStatement p = (PreparedStatement) Db_Koneksi.getKoneksi().prepareStatement(sql);

            ResultSet a = p.executeQuery(sql);    
            
            if (a.next()) {
                fkodetransaksi = a.getString(1);
                txtKTransaksiTerakhir.setText(" " +fkodetransaksi);
            }                     
            
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage());
        }            
      }
      
      public void countPriceDisplay(){
          try{
            Statement stat = (Statement) Db_Koneksi.getKoneksi().createStatement();
            String sql = "select SUM(harga_total) from temporder";
            PreparedStatement p = (PreparedStatement) Db_Koneksi.getKoneksi().prepareStatement(sql);
            
            ResultSet a = p.executeQuery(sql);    
            
            if (a.next()) {
                hasil = a.getInt(1);
                fhasil = Integer.toString(hasil);
                txtLabelHarga.setText("Rp "+fhasil);
            }                     
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage());
        }              
      }
      
        public void Kembalian(){
            bayar = Integer.parseInt(txtBayar.getText());
            kembalian = bayar - hasil;
             fkembalian = Integer.toString(kembalian);
            txtKembalian.setText("Kembalian : Rp " +fkembalian);
            JOptionPane.showMessageDialog(null, "Kembalian = Rp" +fkembalian);
        }
      
      public void saveDataToDetailTransaksi(){
         
        try{
            Statement stat = (Statement) Db_Koneksi.getKoneksi().createStatement();
            String sql = "insert into detail_transaksi select*from temporder";
            PreparedStatement p = (PreparedStatement) Db_Koneksi.getKoneksi().prepareStatement(sql);
            p.executeUpdate();
            getData();
            
            Reset();
            JOptionPane.showMessageDialog(null, "Pesanan diproses! Tekan OK ");
            
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage());
        }   
        
        txtLabelHarga.setText("");
    }
      
     public void saveData(){
         
         loadData();
        
        try{
            Statement stat = (Statement) Db_Koneksi.getKoneksi().createStatement();
            String sql = "insert into temporder values ('"+cust+"', '"+menu+"', '"+jumlah+"', '"+keterangan+"', '"+harga_menu+"', '"+harga_total+"', '"+kode_transaksi+"')";
            PreparedStatement p = (PreparedStatement) Db_Koneksi.getKoneksi().prepareStatement(sql);
            p.executeUpdate();
            getData();          
            Reset();
            
        }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage());
        }             
        jButton7.setEnabled(true);
    }
     
    
     public void dataSelect(){
        int i = tbl_makanan.getSelectedRow();
        if (i == -1){
            return;
        }
        txtHargaMenu.setText(""+model2.getValueAt(i, 1));
        txtMenu.setText(""+model2.getValueAt(i, 0));          
    }
     
     public void dataSelectOrder(){
        int i = temporder.getSelectedRow();
        if (i == -1){
            return;
        }
        txtCust.setText(""+model.getValueAt(i, 0));
        txtMenu.setText(""+model.getValueAt(i, 1));
        txtJml.setText(""+model.getValueAt(i, 2));
        txtKet.setText(""+model.getValueAt(i, 3));
        txtHargaMenu.setText(""+model.getValueAt(i, 4));
        txtHargaTotal.setText(""+model.getValueAt(i, 5));
    }
     
    public void updateData(){
        
        hitungHargaTotal();
        loadData();
        
        try {
            Statement stat = (Statement) Db_Koneksi.getKoneksi().createStatement();
            String sql = "update temporder set jumlah = '"+jumlah+"', keterangan = '"+keterangan+"', harga_total = '"+harga_total+"' where menu = '"+menu+"'";
            
            PreparedStatement p = (PreparedStatement) Db_Koneksi.getKoneksi().prepareStatement(sql);
            p.executeUpdate();
            getData();
            
            Reset();
            JOptionPane.showMessageDialog(null, "Data berhasil diupdate!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public void deleteData(){
        loadData();
        
        int pesan = JOptionPane.showConfirmDialog(null, "Anda yakin menghapus menu " +menu+" dari daftar pesanan?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION);
        if(pesan == JOptionPane.OK_OPTION){
            
            try {
                Statement stat = (Statement) Db_Koneksi.getKoneksi().createStatement();
                String sql = "delete from temporder where menu = '"+menu+"'";

                PreparedStatement p = (PreparedStatement) Db_Koneksi.getKoneksi().prepareStatement(sql);
                p.executeUpdate();
                getData();

                Reset();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
            } catch (SQLException e) {
              JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }
     
     public void hitungHargaTotal(){
         
         harga_menu = Integer.parseInt(txtHargaMenu.getText());
         jumlah = Integer.parseInt(txtJml.getText());
         harga_total = (int) jumlah*harga_menu;
         txtHargaTotal.setText(""+harga_total);     
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel logo;
    private javax.swing.JTable tbl_makanan;
    private javax.swing.JTable temporder;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtCust;
    private javax.swing.JTextField txtHargaMenu;
    private javax.swing.JTextField txtHargaTotal;
    private javax.swing.JTextField txtJml;
    private javax.swing.JTextField txtKTransaksiTerakhir;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtKet;
    private javax.swing.JTextField txtKodeTransaksi;
    private javax.swing.JTextField txtLabelHarga;
    private javax.swing.JTextField txtMenu;
    // End of variables declaration//GEN-END:variables
}
